sonar.projectKey=devops-ngawi_TubesWebpro
sonar.organization=devops-ngawi

sonar.sources=backend/express_logilearn/src
sonar.tests=backend/express_logilearn/test

sonar.javascript.lcov.reportPaths=backend/express_logilearn/coverage/lcov.info

sonar.host.url=https://sonarcloud.io